import Head from "next/head";
import ProblemTable from "~/components/table/ProblemTable";

import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading, isError } = api.problem.allProblems.useQuery();

  if (isLoading || isError) return <></>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex h-12 items-center bg-primary px-16 text-primary-foreground">
        <h1 className=" text-lg font-bold tracking-tight">
          BYU CPC Kattis Problem Archive
        </h1>
      </header>
      <main className="px-16 py-8 text-black">
        <ProblemTable data={data} />
      </main>
    </>
  );
}
