import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading, isError } = api.problem.allProblems.useQuery();

  if (isLoading || isError) return <></>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-black">
        <h1>Problems</h1>
        {data.map((problem) => (
          <div key={problem.id}>
            <h2>{problem.title}</h2>
            <p>{problem.difficulty}</p>
            {problem.tags.map((tag) => (
              <span key={tag.id}>{tag.name}</span>
            ))}
          </div>
        ))}
      </main>
    </>
  );
}
